import {
  AceOfClubs,
  EightOfClubs,
  FiveOfClubs,
  FourOfClubs,
  JackOfClubs,
  KingOfClubs,
  NineOfClubs,
  QueenOfClubs,
  SevenOfClubs,
  SixOfClubs,
  TenOfClubs,
  ThreeOfClubs,
  TwoOfClubs,
} from "./suits/clubs";
import {
  AceOfDiamonds,
  EightOfDiamonds,
  FiveOfDiamonds,
  FourOfDiamonds,
  JackOfDiamonds,
  KingOfDiamonds,
  NineOfDiamonds,
  QueenOfDiamonds,
  SevenOfDiamonds,
  SixOfDiamonds,
  TenOfDiamonds,
  ThreeOfDiamonds,
  TwoOfDiamonds,
} from "./suits/diamonds";
import {
  AceOfHearts,
  EightOfHearts,
  FiveOfHearts,
  FourOfHearts,
  JackOfHearts,
  KingOfHearts,
  NineOfHearts,
  QueenOfHearts,
  SevenOfHearts,
  SixOfHearts,
  TenOfHearts,
  ThreeOfHearts,
  TwoOfHearts,
} from "./suits/hearts";
import {
  AceOfSpades,
  EightOfSpades,
  FiveOfSpades,
  FourOfSpades,
  JackOfSpades,
  KingOfSpades,
  NineOfSpades,
  QueenOfSpades,
  SevenOfSpades,
  SixOfSpades,
  TenOfSpades,
  ThreeOfSpades,
  TwoOfSpades,
} from "./suits/spades";

/** All 52 playing cards as a runtime array, ordered by suit (hearts, diamonds, clubs, spades). */
export const ALL_CARDS = [
  AceOfHearts,
  TwoOfHearts,
  ThreeOfHearts,
  FourOfHearts,
  FiveOfHearts,
  SixOfHearts,
  SevenOfHearts,
  EightOfHearts,
  NineOfHearts,
  TenOfHearts,
  JackOfHearts,
  QueenOfHearts,
  KingOfHearts,
  AceOfDiamonds,
  TwoOfDiamonds,
  ThreeOfDiamonds,
  FourOfDiamonds,
  FiveOfDiamonds,
  SixOfDiamonds,
  SevenOfDiamonds,
  EightOfDiamonds,
  NineOfDiamonds,
  TenOfDiamonds,
  JackOfDiamonds,
  QueenOfDiamonds,
  KingOfDiamonds,
  AceOfClubs,
  TwoOfClubs,
  ThreeOfClubs,
  FourOfClubs,
  FiveOfClubs,
  SixOfClubs,
  SevenOfClubs,
  EightOfClubs,
  NineOfClubs,
  TenOfClubs,
  JackOfClubs,
  QueenOfClubs,
  KingOfClubs,
  AceOfSpades,
  TwoOfSpades,
  ThreeOfSpades,
  FourOfSpades,
  FiveOfSpades,
  SixOfSpades,
  SevenOfSpades,
  EightOfSpades,
  NineOfSpades,
  TenOfSpades,
  JackOfSpades,
  QueenOfSpades,
  KingOfSpades,
] as const;

/** Union type of all 52 playing card objects, derived from the runtime ALL_CARDS array. */
export type PlayingCard = (typeof ALL_CARDS)[number];

export type Suit = PlayingCard["suit"];
export type Rank = PlayingCard["rank"];
