import {
  AceOfClubs,
  EightOfClubs,
  FiveOfClubs,
  FourOfClubs,
  JackOfClubs,
  KingOfClubs,
  NineOfClubs,
  QueenOfClubs,
  SevenOfClubs,
  SixOfClubs,
  TenOfClubs,
  ThreeOfClubs,
  TwoOfClubs,
} from "../suits/clubs";
import {
  AceOfDiamonds,
  EightOfDiamonds,
  FiveOfDiamonds,
  FourOfDiamonds,
  JackOfDiamonds,
  KingOfDiamonds,
  NineOfDiamonds,
  QueenOfDiamonds,
  SevenOfDiamonds,
  SixOfDiamonds,
  TenOfDiamonds,
  ThreeOfDiamonds,
  TwoOfDiamonds,
} from "../suits/diamonds";
import {
  AceOfHearts,
  EightOfHearts,
  FiveOfHearts,
  FourOfHearts,
  JackOfHearts,
  KingOfHearts,
  NineOfHearts,
  QueenOfHearts,
  SevenOfHearts,
  SixOfHearts,
  TenOfHearts,
  ThreeOfHearts,
  TwoOfHearts,
} from "../suits/hearts";
import {
  AceOfSpades,
  EightOfSpades,
  FiveOfSpades,
  FourOfSpades,
  JackOfSpades,
  KingOfSpades,
  NineOfSpades,
  QueenOfSpades,
  SevenOfSpades,
  SixOfSpades,
  TenOfSpades,
  ThreeOfSpades,
  TwoOfSpades,
} from "../suits/spades";

export const intuitiva = {
  name: "Intuitiva Santi",
  order: [
    SevenOfHearts,
    QueenOfHearts,
    KingOfHearts,
    TenOfDiamonds,
    FiveOfHearts,
    JackOfHearts,
    TenOfClubs,
    EightOfHearts,
    TenOfSpades,
    AceOfHearts,
    SevenOfSpades,
    QueenOfSpades,
    KingOfSpades,
    AceOfDiamonds,
    FiveOfSpades,
    JackOfSpades,
    AceOfClubs,
    EightOfSpades,
    AceOfSpades,
    TwoOfHearts,
    NineOfClubs,
    SixOfHearts,
    SixOfDiamonds,
    TwoOfDiamonds,
    NineOfSpades,
    SixOfSpades,
    TwoOfClubs,
    SixOfClubs,
    TwoOfSpades,
    ThreeOfHearts,
    SevenOfClubs,
    QueenOfClubs,
    KingOfClubs,
    ThreeOfDiamonds,
    FiveOfClubs,
    JackOfClubs,
    ThreeOfClubs,
    EightOfClubs,
    ThreeOfSpades,
    FourOfHearts,
    SevenOfDiamonds,
    QueenOfDiamonds,
    KingOfDiamonds,
    FourOfDiamonds,
    FiveOfDiamonds,
    JackOfDiamonds,
    FourOfClubs,
    EightOfDiamonds,
    FourOfSpades,
    NineOfDiamonds,
    NineOfHearts,
    TenOfHearts,
  ] as const,
};
