import {
  AceOfClubs,
  EightOfClubs,
  FiveOfClubs,
  FourOfClubs,
  JackOfClubs,
  KingOfClubs,
  NineOfClubs,
  QueenOfClubs,
  SevenOfClubs,
  SixOfClubs,
  TenOfClubs,
  ThreeOfClubs,
  TwoOfClubs,
} from '../suits/clubs';
import {
  AceOfDiamonds,
  EightOfDiamonds,
  FiveOfDiamonds,
  FourOfDiamonds,
  JackOfDiamonds,
  KingOfDiamonds,
  NineOfDiamonds,
  QueenOfDiamonds,
  SevenOfDiamonds,
  SixOfDiamonds,
  TenOfDiamonds,
  ThreeOfDiamonds,
  TwoOfDiamonds,
} from '../suits/diamonds';
import {
  AceOfHearts,
  EightOfHearts,
  FiveOfHearts,
  FourOfHearts,
  JackOfHearts,
  KingOfHearts,
  NineOfHearts,
  QueenOfHearts,
  SevenOfHearts,
  SixOfHearts,
  TenOfHearts,
  ThreeOfHearts,
  TwoOfHearts,
} from '../suits/hearts';
import {
  AceOfSpades,
  EightOfSpades,
  FiveOfSpades,
  FourOfSpades,
  JackOfSpades,
  KingOfSpades,
  NineOfSpades,
  QueenOfSpades,
  SevenOfSpades,
  SixOfSpades,
  TenOfSpades,
  ThreeOfSpades,
  TwoOfSpades,
} from '../suits/spades';

export const memorandum = {
  name: 'Memorandum',
  order: [
    JackOfSpades,
    SevenOfClubs,
    TenOfHearts,
    AceOfDiamonds,
    FourOfClubs,
    SevenOfHearts,
    FourOfDiamonds,
    AceOfSpades,
    FourOfHearts,
    SevenOfDiamonds,
    FourOfSpades,
    AceOfHearts,
    TenOfDiamonds,
    SevenOfSpades,
    JackOfClubs,
    KingOfDiamonds,
    TenOfSpades,
    EightOfClubs,
    JackOfHearts,
    AceOfClubs,
    KingOfSpades,
    FiveOfClubs,
    EightOfHearts,
    ThreeOfDiamonds,
    QueenOfSpades,
    KingOfHearts,
    NineOfClubs,
    QueenOfHearts,
    SixOfClubs,
    NineOfHearts,
    TwoOfDiamonds,
    ThreeOfClubs,
    SixOfHearts,
    FiveOfDiamonds,
    TwoOfSpades,
    ThreeOfHearts,
    EightOfDiamonds,
    FiveOfSpades,
    KingOfClubs,
    JackOfDiamonds,
    EightOfSpades,
    TenOfClubs,
    TwoOfClubs,
    FiveOfHearts,
    SixOfDiamonds,
    ThreeOfSpades,
    TwoOfHearts,
    NineOfDiamonds,
    SixOfSpades,
    QueenOfClubs,
    QueenOfDiamonds,
    NineOfSpades,
  ] as const,
};
